# Generated by Django 4.1.1 on 2022-10-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaisecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RaisecQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisec_question', models.CharField(max_length=255)),
                ('raisec_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raisec.raisecgroup')),
            ],
        ),
    ]
